# Generated by Django 5.1.3 on 2024-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
