# Generated by Django 5.1.3 on 2024-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookcollection',
            name='status',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Completed', 'Completed'), ('Wishlist', 'Wishlist')], default='Wishlist', max_length=15),
        ),
    ]
